#version 450
#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_GOOGLE_cpp_style_line_directive : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

// Unique invocation id. Used to determine the index of the PRNG seed for this
// invocation in `prng[]`.
uint invocation_uid =
    gl_GlobalInvocationID.y * gl_NumWorkGroups.x * gl_WorkGroupSize.x +
    gl_GlobalInvocationID.x;

layout(set = 0, binding = 0, std430) buffer PRNGSeed { uint64_t prng[]; };
layout(set = 0, binding = 1, std430) buffer Result { uint64_t result[]; };
